/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const PokemonDetailsNameLazyImport = createFileRoute('/pokemon-details/$name')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PokemonDetailsNameLazyRoute = PokemonDetailsNameLazyImport.update({
  path: '/pokemon-details/$name',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/pokemon-details.$name.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pokemon-details/$name': {
      id: '/pokemon-details/$name'
      path: '/pokemon-details/$name'
      fullPath: '/pokemon-details/$name'
      preLoaderRoute: typeof PokemonDetailsNameLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  PokemonDetailsNameLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pokemon-details/$name"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pokemon-details/$name": {
      "filePath": "pokemon-details.$name.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
