/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { createFileRoute } from '@tanstack/react-router'

// Import Routes
import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PokemonExplorerIndexImport } from './routes/pokemon-explorer/index'

// Create Virtual Routes

const PokemonExplorerPokemonDetailsNameLazyImport = createFileRoute(
  '/pokemon-explorer/pokemon-details/$name'
)()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute
} as any)

const PokemonExplorerIndexRoute = PokemonExplorerIndexImport.update({
  id: '/pokemon-explorer/',
  path: '/pokemon-explorer/',
  getParentRoute: () => rootRoute
} as any)

const PokemonExplorerPokemonDetailsNameLazyRoute = PokemonExplorerPokemonDetailsNameLazyImport.update({
  id: '/pokemon-explorer/pokemon-details/$name',
  path: '/pokemon-explorer/pokemon-details/$name',
  getParentRoute: () => rootRoute
} as any).lazy(() => import('./routes/pokemon-explorer/pokemon-details.$name.lazy').then(d => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pokemon-explorer/': {
      id: '/pokemon-explorer/'
      path: '/pokemon-explorer'
      fullPath: '/pokemon-explorer'
      preLoaderRoute: typeof PokemonExplorerIndexImport
      parentRoute: typeof rootRoute
    }
    '/pokemon-explorer/pokemon-details/$name': {
      id: '/pokemon-explorer/pokemon-details/$name'
      path: '/pokemon-explorer/pokemon-details/$name'
      fullPath: '/pokemon-explorer/pokemon-details/$name'
      preLoaderRoute: typeof PokemonExplorerPokemonDetailsNameLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemon-explorer': typeof PokemonExplorerIndexRoute
  '/pokemon-explorer/pokemon-details/$name': typeof PokemonExplorerPokemonDetailsNameLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokemon-explorer': typeof PokemonExplorerIndexRoute
  '/pokemon-explorer/pokemon-details/$name': typeof PokemonExplorerPokemonDetailsNameLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pokemon-explorer/': typeof PokemonExplorerIndexRoute
  '/pokemon-explorer/pokemon-details/$name': typeof PokemonExplorerPokemonDetailsNameLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokemon-explorer' | '/pokemon-explorer/pokemon-details/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokemon-explorer' | '/pokemon-explorer/pokemon-details/$name'
  id: '__root__' | '/' | '/pokemon-explorer/' | '/pokemon-explorer/pokemon-details/$name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokemonExplorerIndexRoute: typeof PokemonExplorerIndexRoute
  PokemonExplorerPokemonDetailsNameLazyRoute: typeof PokemonExplorerPokemonDetailsNameLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokemonExplorerIndexRoute: PokemonExplorerIndexRoute,
  PokemonExplorerPokemonDetailsNameLazyRoute: PokemonExplorerPokemonDetailsNameLazyRoute
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pokemon-explorer/",
        "/pokemon-explorer/pokemon-details/$name"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pokemon-explorer/": {
      "filePath": "pokemon-explorer/index.tsx"
    },
    "/pokemon-explorer/pokemon-details/$name": {
      "filePath": "pokemon-explorer/pokemon-details.$name.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
