/* prettier-ignore-start */

/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
import { createFileRoute } from '@tanstack/react-router'

// Import Routes
import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const PokemonDetailsNameLazyImport = createFileRoute('/pokemon-details/$name')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute
} as any)

const PokemonDetailsNameLazyRoute = PokemonDetailsNameLazyImport.update({
  path: '/pokemon-details/$name',
  getParentRoute: () => rootRoute
} as any).lazy(() => import('./routes/pokemon-details.$name.lazy').then(d => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pokemon-details/$name': {
      id: '/pokemon-details/$name'
      path: '/pokemon-details/$name'
      fullPath: '/pokemon-details/$name'
      preLoaderRoute: typeof PokemonDetailsNameLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokemon-details/$name': typeof PokemonDetailsNameLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokemon-details/$name': typeof PokemonDetailsNameLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pokemon-details/$name': typeof PokemonDetailsNameLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pokemon-details/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokemon-details/$name'
  id: '__root__' | '/' | '/pokemon-details/$name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokemonDetailsNameLazyRoute: typeof PokemonDetailsNameLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokemonDetailsNameLazyRoute: PokemonDetailsNameLazyRoute
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pokemon-details/$name"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pokemon-details/$name": {
      "filePath": "pokemon-details.$name.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
